### ISSUE TITLE
Packages with icons not appearing anywhere

### ISSUE THREAD

**Issue by Veight** [UsrLightmann/IAmLazy#13]
This is happening on the latest version from the big boss repo. I did a standard backup and restore. Did a respring and uicache(?). Tried doing an LDRestart and shut the phone off and back on. The tweaks show they are installed in Zebra.

**Comment by UsrLightmann** [comment]
@Veight, did doing what I suggested above fix this for you?

**Comment by UsrLightmann** [comment]
Fixed in v1.4.0.
