### ISSUE TITLE
doesn't restore?

### ISSUE THREAD

**Issue by 3m4r5** [UsrLightmann/IAmLazy#2]
I made a back up, restored rootfs, installed iamlazy again and chose 'uicache & respring' & when it finishes nothing is installed!

what I'm doing wrong?

**Comment by UsrLightmann** [comment]
This is a known issue that has since been fixed in v1.0.1 which should've been published today but wasn't. Am trying to get that resolved ASAP. Apologies for the delay

**Comment by UsrLightmann** [comment]
Update just went live. Please give it a go and let me know if it resolved your issue.

**Comment by 3m4r5** [comment]
@UsrLightmann it works fine now, thank you
