### ISSUE TITLE
Unable to create backup

### ISSUE THREAD

**Issue by booleangit** [UsrLightmann/IAmLazy#3]
Since your latest update, the backup procedure stopped working. After *almost* completing the backup, I got the error message: archive doesn't look right. I've rebooted the phone and tried again, but got the same message.

**Comment by UsrLightmann** [comment]
My bad. A quick fix has been sent out for publishing. Will probably be live later tonight or early tomorrow.

**Comment by UsrLightmann** [comment]
Update is live. Please let me know if it resolved your issue.

**Comment by Louloucest** [comment]
The 1.0.1.1 don’t fix it 
Can you let the downgrade??
The 1st 1.0 was the best

**Comment by booleangit** [comment]
Thanks for the effort, but it didn't fix the issue. I got the exact same error.

**Comment by UsrLightmann** [comment]
Damn. Okay. Could you shoot me an email? (lightmanns11@gmail.com)

**Comment by booleangit** [comment]
I'm currently in bed (it's 1:37 AM over here), but I've already emailed you before I opened this ticket on git. Steven is the name ;)

**Comment by UsrLightmann** [comment]
The 'estimate' code did more harm than good so I've just removed it. v1.0.1.2, whenever it's published, will resolve this.

**Comment by booleangit** [comment]
Are you sure you've submitted it? It has almost been 12 hours ago, so it should be visible by now. Not that I'm in a hurry, but I just noticed it isn't published yet.

**Comment by UsrLightmann** [comment]
It's live now

**Comment by UsrLightmann** [comment]
Sure thing. I really just went in a big circle: started w/ no post-backup verification, added verification, attempted to quickly fix verification (and largely failed), removed (most of) the verification. It was flawed from the start. Sorry for all the trouble.


And, yeah, the generic directory path is intentional. May make it specific in the future though. Thanks for reminding me!
