### ISSUE TITLE
I get this error no matter what I do and there isn’t even a folder for the tweak in the stated directory.

### ISSUE THREAD

**Issue by greatbritmerica** [UsrLightmann/IAmLazy#5]
![D73473CA-0202-4EBE-9785-396E083DA068](https://user-images.githubusercontent.com/64992153/120112632-9fed5480-c144-11eb-8a06-5e6044ca5174.png)

**Comment by UsrLightmann** [comment]
Open your terminal of choice (NewTerm or MTerm) and type the following:

- `su` (and enter your root password)
- `chown mobile:mobile Documents/`

Then try making a backup again.
