### ISSUE TITLE
Recent 1.1.0 crashes during backup creation

### ISSUE THREAD

**Issue by kid-pro-kuo** [UsrLightmann/IAmLazy#6]
Prefacing with the fact that I love this tweak because I am indeed lazy.

With the recent upgrade to 1.1.0, making a new backup will cause the tweak to crash during the second step of pulling in all the user packages, i.e. Settings app crashes. My only other piece of evidence is that no new backup file seems to be created in the save directory.

Happy to dig further if needed. I’m on iPhone 12 Pro Max / iOS 14.1 / Taurine+Sileo

**Comment by UsrLightmann** [comment]
Thanks for reporting this! 

Two things: 1) just to confirm, it's crashing during the "gathering files for ..." step, yeah? 2) could you provide a list of your currently installed tweaks?

**Comment by booleangit** [comment]
I'm experiencing the same issue on an iPhone 12 mini running iOS 14.1 using unc0ver. After the first step it fails. It just crashes without Cr4shed catching it.

**Comment by UsrLightmann** [comment]
I have a test build ready. If either of you would like to give it a go, please shoot me an email

**Comment by kid-pro-kuo** [comment]
> Thanks for reporting this! 
> 
> Three things: 1) just to confirm, it's crashing during the "gathering files for ..." step, yeah? 2) could you provide a list of your currently installed tweaks? 3) could you provide a crash log? 

1) yeah, it's the "Gathering files for user packages" step. It'll be running for a few minutes before crashing 

2) here you go:

applist
awzedesign.zenira
co.dynastic.ios.lib.flora
com.amywhile.signalreborn
com.cachetes.oxyg3n
com.chr1s.atlas
com.cokepokes.appstoreplusplus
com.cokepokes.libnotifications
com.creaturecoding.libcspreferences
com.creaturesurvive.libcscolorpicker
com.cydiageek.skinnysettings
com.daveapps.quitall
com.dozenzb.nzbunity
com.fenix.spaceui
com.foxfort.darkgmaps
com.foxfort.foxforttools
com.foxfort.libfoxfortsplash
com.foxfort.libfoxfortutils
com.foxfort.lumi
com.ginsu.dodo
com.icraze.hestia
com.initwithframe.velvet
com.kurrt.safeshutdown
com.lacertosusrepo.libdeusprefs
com.lacertosusrepo.libellum
com.lacertosusrepo.tweakcount
com.laughingquoll.prefixui
com.laughingquoll.prysm
com.matchstic.xenhtml
com.maxpatchs.moxy
com.megadev.sentinel
com.muirey03.cr4shed
com.muirey03.libmryipc
com.opa334.ccsupport
com.opa334.libundirect
com.opa334.safariplus
com.paraskcd.influentialhs
com.peterdev.libpddokdo
com.rileytestut.altdaemon
com.rpgfarm.a-bypass
com.rpgfarm.a-font
com.rpgfarm.libaptoast
com.shepgoba.settingswidgets
com.spark.libsparkapplist
com.spark.libsparkcolourpicker
com.spark.snowboard
com.synnyg.backupaz4
com.tigisoftware.filza
com.titand3v.libtitand3vuniversal
com.titand3v.speedy
com.twickd.ethan-whited.catalina
com.twickd.quix.noclutter
com.twickd.ziadali.dotty
com.vlo.lux
com.whyms.thine
dev.ayden.ios.lib.sys.aurora
dev.ayden.ios.tweak.starfish-lite
hi.my.name.is.ubik.kalm
me.ahmedbafkir.dleasy
me.alfhaily.cercube
me.alfhaily.rocket
me.apptapp.installer
me.lightmann.iamlazy
net.limneos.libbulletin
net.pane.l.evilscheme
ws.hbang.alderis
ws.hbang.common
xyz.royalapps.prokeys

3) what's funny is that Cr4shed doesn't have a record of the process failing. Is there another place I should be looking for a crash log?

**Comment by UsrLightmann** [comment]
Thanks! Nope, if it didn't show up then Cr4shed didn't catch it. No worries.

Someone else managed to grab one and it's a memory usage issue. I've pinned down the culprit code block and am working on a fix. I have one ready now, if you'd like to try it.

**Comment by kid-pro-kuo** [comment]
@UsrLightmann I'd be happy to g CBD FYIy and test. This is actually the first time I've filed a bug or interacted with another person on a public repo. I wasn't sure how to find your email address...

**Comment by UsrLightmann** [comment]
No worries! 

If you click on one of my packages in your package manager and then click on my name it should open up an email (at least, that's the case with Cydia).

To save you the click, it's lightmanns11@gmail.com

**Comment by UsrLightmann** [comment]
Just sent v1.1.1 out for publishing (should be live sometime in the next 12 hours). 

It aims to fix the root cause of the crashing. Once it's available, please let me know if it resolves the issue. 

And thanks again for your help testing and bringing this to my attention!

**Comment by booleangit** [comment]
The updated version no longer crashes, but takes considerably longer to complete. Normally a standard backup would take about 500sec and results in a ~760MB archive. Now it takes over 2400sec and results in a ~4.6GB archive.

**Comment by UsrLightmann** [comment]
@booleangit I've had a few people mention the drastic increase in backup time...will look into that. 

With regard to the size, I hadn't noticed a huge difference in my testing. Will take another look.

**Comment by UsrLightmann** [comment]
@booleangit I have a test build ready. Would you mind shooting me an email? Thanks in advance!

**Comment by UsrLightmann** [comment]
Fixed crashing in v1.1.1 and fixed large, lengthy backups in v1.1.2.
