### ISSUE TITLE
Ultimate battery drain benchmark

### ISSUE THREAD

**Issue by booleangit** [UsrLightmann/IAmLazy#7]
My apologies for missing your reply to the previous issue.

I'm not sure if it's now working as it supposed to and before it wasn't, or vice versa. Since the latest two updates, the "standard" backup produces a ~4.6GB file, which before only was ~740MB. As a result it takes considerably longer and drains the battery faster than the most demanding battery stress test. If this was intended behavior all is well, but I just wanted to point it out.

**Comment by UsrLightmann** [comment]
No worries. 

Have a handful of questions for ya:
1. Are we talking about v1.1.2?
2. Can you share your tweak list?
3. Is that ~4.6 GB file a new file or is the same backup being overwritten every time?  
4. Does renaming the "me.lightmann.iamlazy" directory in /var/mobile/Documents to something like "me.lightmann.iamlazy-old" resolve the issue? 

Thanks in advance!

**Comment by UsrLightmann** [comment]
Should be fixed with v1.2.0 which will be available in the next 12 hours. 

Please let me know if it resolves your issue.

**Comment by UsrLightmann** [comment]
Closing due to lack of response.
