### ISSUE TITLE
Iamlazy Is not working properly from the homes screen icon

### ISSUE THREAD

**Issue by elvergal** [UsrLightmann/IAmLazy#8]
Hello... There is a bug on the latest version (only affects if I use the tweak from the homescreen icon)... It's not possible to create a new backup not read the previously stored backups... please fix it
Regards

![EA369428-6D95-49E4-8039-50CEC04D7055](https://user-images.githubusercontent.com/63084403/126506501-545e5d5d-a353-424c-bfe5-b46247544480.png)

**Comment by UsrLightmann** [comment]
Hey, thanks for reporting this! 

You said this only occurs with the latest version (v1.3.0), yeah?

Also, 1) did you change Documents/ to have mobile ownership? 2) can you share the output of "stat -c '%a' /var/mobile/Documents" please?

**Comment by UsrLightmann** [comment]
Fixed in v1.3.1 which will be up either later tonight or early tomorrow.
