### ISSUE TITLE
“var/mobile/Documents is not writable” but mobile owns dir 

### ISSUE THREAD

**Issue by HexCodeFFF** [UsrLightmann/IAmLazy#9]
![5F363917-0F0C-42A1-A483-4B581FC0D168](https://user-images.githubusercontent.com/35177464/126573763-88af8328-51c8-4e7d-a042-fa2e3b9c7668.png)
![49028C02-DFE9-429F-8B66-A9E2E29CDC80](https://user-images.githubusercontent.com/35177464/126573768-8a39673f-b961-4898-937c-38959aaaaa02.png)

No crash information or anything. according to Filza, mobile owns the dir

**Comment by UsrLightmann** [comment]
Hey, thanks for reporting this!

I got to work on it earlier today. It has been fixed and said patched version (v1.3.1) will be up either later tonight or early tomorrow.
